### ISSUE TITLE
HOL - unguided

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Data-Platform-upgrade-and-migration#10]
Need one more level in the TOC please - to include Tasks to complete and Exit criteria.

**Comment by kylebunting** [comment]
Adding this extra level will not work in GitHub markdown. I can add the links to the TOC, but they will not resolve to the correct place in the documents because the headers (Tasks to complete and Exit criteria) are not unique in the document. For TOC links to work, we would need each Tasks to Complete and Exit criteria header to be unique within the document.

**Comment by DawnmarieDesJardins** [comment]
Got it!  Thanks for the heads up and explanation.  Closing issues.
