### ISSUE TITLE
Issue with Oracle download link:- Exercise 4: Setup Oracle 11g Express Edition

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Data-Platform-upgrade-and-migration#16]
1. Oracle download link for Oracle 11g XE takes us to the latest edition of XE for Linux, it should point to Windows.
2. The path to lab files has a minor inaccuracy in the Oracle Script lab for Northwind
3. Execute SQL in fusion via Visual Studio doesn’t work well, After the  execute selection for script 4, we had to do execute selection for the rest of the scripts. The execute (all) button did not work anymore.

**Comment by kylebunting** [comment]
1. The download link for Oracle 11gR2 XE has been updated. Oracle changes these frequently, so all we can do is update them when they change.
2. Path to the Oracle Scripts folder under lab files has been updated to reflect the correct path.
3. Unfortunately, I cannot update this because Oracle Tools for Visual Studio 2017 are not compatible with Visual Studio Community edition, so Fusion is the only tool available to perform these actions in Visual Studio Community at this time. I have not seen the issue you described before, but I know Fusion is not an ideal tool.
